# Generated by Django 3.2.9 on 2021-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20211211_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'สินค้า', 'verbose_name_plural': 'ข้อมูลสินค้า'},
        ),
        migrations.AddField(
            model_name='product',
            name='timeCook',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
