# Generated by Django 2.2.14 on 2021-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_product_timecook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'สินค้า', 'verbose_name_plural': 'ข้อมูลสินค้า'},
        ),
    ]
