# Generated by Django 2.2.14 on 2021-12-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_category_image'),
        ('homepage', '0004_auto_20211211_2316'),
    ]

    operations = [
    ]
